TREP-LABS/realdrip-backend

- .gitIgnore
- .travis.yml
- README.md
- jest.config.js
- package-lock.json
- package.json
- src/api/v1/tests/realdrip_v1.test.js
- Merges the develop branch into master
> Merge develop into master

- .travis.yml
- src/http/app.js
- src/services/user.js
- src/tests/health.test.js
- src/tests/postAdminUser.test.js
- The admin signup API endpoint works fine, however, the response sent after successful signup does not correlate with what is in the swagger API spec, this PR attempts to fix that.
- As a quick fix, this PR also enables CORS for browser clients
> Update admin signup response

- .env.example
- .travis.yml
- package-lock.json
- package.json
- src/http/app.js
- src/http/start.js
- src/services/config.js
- src/services/email/index.js
- src/services/email/templates/emailAddressValidation.js
- src/services/user.js
- src/tests/health.test.js
- src/tests/postAdminUser.test.js
- Adds an email service that can be used to send mails
- Use the email service to send mail to the user for email-address verification after signup
- Setup the app(some new environment variables are required, check `.env.examle`)
- Try signing up with a valid email address 
- After successful signup, you should receive an email notification to confirm your email address
- NB: The functionality of confirming the email address is not yet working, so if you click the button in the email to verify your email, don't be 😞 
- Confirmation mail
> Send mail to verify email address after signup 

- .env.example
- package-lock.json
- src/db/models/user.js
- src/http/config.js
- src/http/controllers/user.js
- src/http/routes.js
- src/http/validations/user.js
- src/services/config.js
- src/services/email/templates/emailAddressValidation.js
- src/services/user.js
- src/tests/postConfirmAccount.test.js
- Implements the API endpoint to confirm a user account
- As described in the API spec [here](https://app.swaggerhub.com/apis/Treplabs/Realdrip/1.0#/Users/get_users_confirm)
[#168358984 ](https://www.pivotaltracker.com/story/show/168358919)
> #168358984 User confirmation api endpoint

- .env.example
- .travis.yml
- package-lock.json
- package.json
- src/http/app.js
- src/http/controllers/user.js
- src/http/start.js
- src/http/validations/user.js
- src/services/user.js
- src/utils/logger.js
- Configure an application logger([Bynyan](https://github.com/trentm/node-bunyan)) with dynamic log levels
- Use the logger to replace all existing `console.log` expressions
- Use the logger to log debug end error messages where needed in the app
[#169063190 ](https://www.pivotaltracker.com/story/show/169063190)
> #169063190 Configure and use logger

- src/db/users/models.js
- src/http/routes.js
- src/services/user.js
- src/tests/postAdminUser.test.js
- src/tests/postConfirmEmail.test.js
- src/tests/postLogin.test.js
- Updates the signup, login and confirmEmail endpoints implementation as well as their tests.
> #169086573 Update existing API endpoint to reflect the changes in API spec

- .eslintrc
- src/db/users/index.js
- src/http/controllers/user.js
- src/http/middlewares/authMiddleware.js
- src/http/routes.js
- src/http/validations/user.js
- src/services/device.js
- src/services/user.js
- src/tests/getDevice.test.js
- src/tests/putHospitalUser.test.js
- Implements "PUT /hospital" API endpoint
- Remove unnecessary eslint inline disabling
- As described in the API spec
> #169089859 Implement "PUT /hospital" API endpoint

- package-lock.json
- package.json
- src/db/users/models.js
- src/http/controllers/index.js
- src/http/controllers/user/allUser.js
- src/http/controllers/user/hospitalUser.js
- src/http/controllers/user/wardUser.js
- src/http/middlewares/authMiddleware.js
- src/http/middlewares/userStatus.js
- src/http/routes.js
- src/http/validations/user.js
- src/services/config.js
- src/services/email/index.js
- src/services/email/templates/newWardUser.js
- src/services/index.js
- src/services/user/allUser.js
- src/services/user/hospitalUser.js
- src/services/user/wardUser.js
- Implements the create ward account API endpoint
- Add a little bit of folder restructuring for user controller and services
> #169178659 Implement create ward account API endpoint

- src/db/index.js
- src/http/controllers/user/wardUser.js
- src/http/middlewares/userStatus.js
- src/http/routes.js
- src/http/validations/user.js
- src/services/user/wardUser.js
- Implements get single ward user API endpoint
- Replace the `isHospitalUser` middleware with a more generic `hasUserPrivledge` middleware
- [169228492 ](https://www.pivotaltracker.com/story/show/169228492)
> #169228492 Get single ward API endpoint

- .travis.yml
- src/http/controllers/user/wardUser.js
- src/http/routes.js
- src/http/validations/user.js
- src/services/user/wardUser.js
- Implement update ward user API endpoint
- [169228192](https://www.pivotaltracker.com/story/show/169228192)
> #169228192 Implement update ward user API endpoint

- src/db/users/index.js
- src/http/controllers/user/wardUser.js
- src/http/routes.js
- src/services/user/allUser.js
- src/services/user/wardUser.js
- Implement get all ward user API endpoint
- [169228556](https://www.pivotaltracker.com/story/show/169228556)
> #169228556 Get all ward users API endpoint

- src/http/controllers/user/allUser.js
- src/http/routes.js
- src/http/validations/user.js
- src/services/user/allUser.js
- Implement update user password API endpoint
- [168358963](https://www.pivotaltracker.com/story/show/168358963)
> #168358963 Implement update user password API endpoint

- src/db/index.js
- src/db/infusion/index.js
- src/db/infusion/model.js
- src/http/controllers/index.js
- src/http/controllers/infusion.js
- src/http/routes.js
- src/http/validations/infusion.js
- src/services/infusion.js
- src/tests/getDevice.test.js
- src/tests/infusion.test.js
**What does this PR do?**
- Implement create infusion API endpoint as specified in the spec
**Related Pivotal Tracker Story**
[#169257401](https://www.pivotaltracker.com/story/show/169257401)
> #169257401 Implement Create Infusion

- src/http/controllers/infusion.js
- src/http/routes.js
- src/services/infusion.js
- src/tests/infusion.test.js
- Implements get all infusion endpoint as specified in the api spec
[#169258328](https://www.pivotaltracker.com/story/show/169258328)
> #169258328 Implement get all infusion API endpoint

- src/db/users/models.js
- src/http/controllers/index.js
- src/http/controllers/user/nurseUser.js
- src/http/routes.js
- src/services/email/index.js
- src/services/email/templates/newNurseUser.js
- src/services/user/nurseUser.js
- Implement create nurse user API endpoint
- Add proper access level control to the get all device API endpoint
- [168358942 ](https://www.pivotaltracker.com/story/show/168358942 )
> #168358942 Implement create nurse user API endpoint

- src/db/infusion/index.js
- src/http/controllers/infusion.js
- src/http/routes.js
- src/http/validations/infusion.js
- src/services/infusion.js
- src/tests/infusion.test.js
- Implements the getSingleInfusion endpoint as specified in the API spec
[#169258562](https://www.pivotaltracker.com/story/show/169258562)
> #169258562 Implements get single infusion 

- src/http/controllers/infusion.js
- src/http/routes.js
- src/http/validations/infusion.js
- src/services/infusion.js
- src/tests/infusion.test.js
**WHAT DOES THIS PR DO ?**
Implements update infusion API endpoint as specified in the API spec
[#169283777](https://www.pivotaltracker.com/story/show/169283777)
> #169283777 Implements update infusion API endpoint

- src/db/infusion/index.js
- src/http/controllers/infusion.js
- src/http/routes.js
- src/http/validations/infusion.js
- src/services/infusion.js
- src/tests/infusion.test.js
Implements delete infusion API endpoint as specified in the API spec
[#169284148](https://www.pivotaltracker.com/story/show/169284148)
> #169284148 Implements delete infusion api endpoint

- src/http/controllers/user/nurseUser.js
- src/http/routes.js
- src/http/validations/user.js
- src/services/user/nurseUser.js
Implements get single nurse user api endpoint
**HOW CAN IT BE TESTED LOCALLY**
According to the way it's described in the API spec
[#169337416](https://www.pivotaltracker.com/story/show/169337416)
> #169337416 Implement get single nurse API endpoint

- src/db/device/model.js
Add `fbDeviceId` to the device schema
[#169257991](https://www.pivotaltracker.com/story/show/169257991)
> #169257991 Add fbDeviceId to device schema

- src/http/controllers/index.js
- src/http/controllers/user/nurseUser.js
- src/http/routes.js
- src/services/user/nurseUser.js
Implements get all nurse user api endpoint as specified in the API spec
[#169337222](https://www.pivotaltracker.com/story/show/169337222)
> #169337222 Implement get all nurse API endpoint

- src/http/controllers/user/nurseUser.js
- src/http/routes.js
- src/http/validations/user.js
- src/services/user/nurseUser.js
Implement update nurse api endpoint
[#169337589](https://www.pivotaltracker.com/story/show/169337589)
> #169337589 Implement update nurse API endpoint

- src/services/infusion.js
- Removes get all infusion from a try catch block
- [#169523994](https://www.pivotaltracker.com/story/show/169523994)
> #169523994 removed try catch from get all infusion

- package.json
- src/db/config.js
- src/http/config.js
- src/tests/setup.js
- src/utils/logger.js
- src/utils/validateEnvironmentVars.js
- Add logic to validate environment variables before starting the app
- Remove default environment variable setting withing application, everything is now in just one place(file),  `validateEnvironmentVar.js`
> #168984294 Validate environment vars before starting application

- src/http/controllers/user/hospitalUser.js
- src/http/routes.js
- src/http/validations/user.js
- src/services/user/hospitalUser.js
- src/tests/users/hospital/updateHospitalUser.test.js
Bug fix: use userId as a params for updating hospital user instead of loggedIn user id
[#169524116](https://www.pivotaltracker.com/story/show/169524116)
> #169524116 userId params for updating hospital user

- .babelrc
- package-lock.json
- package.json
- src/db/setup.js
- Fix console warnings and deprecation warnings when app starts
[#169258209 ](https://www.pivotaltracker.com/story/show/169258209)
> #169258209 fix console warning when app starts

- src/http/controllers/user/nurseUser.js
- src/http/validations/user.js
- Adds validation to create nurse user API endpoint
- [#169524056](https://www.pivotaltracker.com/story/show/169524056)
> #169524056 add validation to create nurse user endpoint

- src/http/routes.js
Pluralized the get all device endpoint as specified in the API spec
[#169524073](https://www.pivotaltracker.com/story/show/169524073)
> #169524073 pluralized get all device endpoint

- src/http/validations/user.js
- Fix an object destructuring bug in create hospital user request body validation
[169524067](https://www.pivotaltracker.com/story/show/169524067)
> #169524067 Improve create hospital user request body validation

- src/http/routes.js
- src/services/user/wardUser.js
- Use a single db query when updating ward user at the service level
- Update user privileges required for updating ward and hospital users such that only a hospital user can update their account and only ward users can update their account 
- [16952398 ](https://www.pivotaltracker.com/story/show/169523986 )
> #169523986 Improve update ward/hospital user db query and access privilege 

- package.json
- src/http/app.js
- src/http/controllers/device.js
- src/http/controllers/infusion.js
- src/http/controllers/user/hospitalUser.js
- src/http/controllers/user/nurseUser.js
- src/http/controllers/user/wardUser.js
- Create an error handler middleware to handle all 500 errors
[169258202](https://www.pivotaltracker.com/story/show/169258202)
> #169258202 Catch 500 error centrally

- package.json
- src/tests/infusion/createInfusion.test.js
- src/tests/infusion/getInfusion.test.js
- src/tests/setup.js
- src/tests/users/hospital/confirmHospitalUserEmail.test.js
- src/tests/users/hospital/createHospitalUser.test.js
- src/tests/users/hospital/updateHospitalUser.test.js
- src/tests/users/login.test.js
- src/tests/utils/testRunner/index.js
- src/tests/utils/testRunner/testCaseSchema.js
- Add a customer test runner
- Use the test runner across existing tests
- [169615541 ](https://www.pivotaltracker.com/story/show/169615541 )
- The test runner can only run test cases structured in a certain way. I'm not sure about the best way to document what the testCase object should look like. Currently, I added a `testCaseSchema.js` file but I'm not sure this is good enough, any suggestions would be appreciated.
> #169615541 Add a custom test runner

- .travis.yml
- src/http/middlewares/authMiddleware.js
- src/http/validations/user.js
- src/tests/genericTestCases/confirmAccessLevelRestriction.js
- src/tests/genericTestCases/confirmAuthRestriction.js
- src/tests/infusion/getInfusion.test.js
- src/tests/users/hospital/updateHospitalUser.test.js
- src/tests/users/ward/createWardUser.test.js
- src/tests/users/ward/getWardUser.test.js
- src/tests/users/ward/updateWardUser.test.js
- Add test for Ward user endpoints
- Add some generic test case that can be reused across multiple 
- [169390728 ](https://www.pivotaltracker.com/story/show/169390728)
> #169390728 Add test for ward user endpoints

- src/utils/validateEnvironmentVars.js
- Set default values for required environment variables
[#169726323](https://www.pivotaltracker.com/story/show/169726323)
> #169726323 Set default values for required environment variables

- .travis.yml
- src/http/validations/user.js
- src/services/user/nurseUser.js
- src/tests/users/nurse/createNurseUser.test.js
- src/tests/users/nurse/getNurseUser.test.js
- src/tests/users/nurse/updateNurseUser.test.js
- Add integration tests for create, getSingle, getAll, and update nurse user endpoint
- [169390740](https://www.pivotaltracker.com/story/show/169390740)
> #169390740 Test nurse user endpoints

- src/http/controllers/infusion.js
- src/http/validations/infusion.js
- src/tests/infusion/createInfusion.test.js
- src/tests/infusion/deleteInfusion.test.js
- src/tests/infusion/getInfusion.test.js
- src/tests/infusion/updateInfusion.test.js
- Implements more use cases for infusion endpoints in it's integration test
- [#169523967](https://www.pivotaltracker.com/story/show/169523967)
> #169523967 Integration test for infusion endpoints

- src/db/device/index.js
- src/http/validations/device.js
- src/services/device.js
- src/tests/device/getdevice.test.js
- src/tests/device/updatedevice.test.js
- Implement integration tests for the following device endpoints
- `GET [ /devices ]`
- `GET [ /devices/{deviceId} ]`
- `PUT [ /devices/{deviceId} ]`
- Refactor getSingleDevice verification
- Remove `try/catch` block from getSingleDevices and getAllDevices service
- [#169523962](https://www.pivotaltracker.com/story/show/169523962)
> #169523962 Implements integration tests for device endpoints

- src/services/user/allUser.js
- src/services/user/hospitalUser.js
- src/services/user/nurseUser.js
- src/services/user/wardUser.js
- src/tests/infusion/createInfusion.test.js
- src/tests/infusion/getInfusion.test.js
- src/tests/users/hospital/createHospitalUser.test.js
- src/tests/users/hospital/updateHospitalUser.test.js
- src/tests/users/login.test.js
- src/tests/users/ward/createWardUser.test.js
- src/tests/users/ward/getWardUser.test.js
- src/tests/users/ward/updateWardUser.test.js
- Replace all occurrence of id to _id
- [169644144](https://www.pivotaltracker.com/story/show/169644144)
> Consistently use _id for resource identifier

- src/db/infusion/index.js
- Remove the version key `__v` from all get requests in the infusion model to avoid overfetching
- [#169835448](https://www.pivotaltracker.com/story/show/169835448)
> #169835448 fix over fetching in infusion model

- src/http/controllers/catchControllerError.js
- src/http/controllers/device.js
- src/http/controllers/infusion.js
- src/http/controllers/user/allUser.js
- src/http/controllers/user/hospitalUser.js
- src/http/controllers/user/nurseUser.js
- src/http/controllers/user/wardUser.js
Abstract the logic of catching and logging controller errors
> #169864965 Improve controller methods

- src/http/validations/user.js
- src/tests/users/updatePassword.test.js
- Integration test for update password endpoint
- [#169523970](https://www.pivotaltracker.com/story/show/169523970)
> #169523970 integration test for update password endpoint

- src/db/index.js
- src/db/infusion/index.js
- src/db/utils.js
- src/http/controllers/infusion.js
- src/services/infusion.js
- src/tests/infusion/deleteInfusion.test.js
- src/tests/infusion/getInfusion.test.js
Implements dynamic query population for the infusion endpoints
- [#170071277](https://www.pivotaltracker.com/story/show/170071277 )
> #170071277 Dynamic infusion query population

- src/http/controllers/device.js
- src/http/routes.js
- src/http/validations/device.js
- src/services/device.js
- src/tests/device/updatedevice.test.js
- Add a validation to make device labels unique at the hospital level making it impossible for same hospital to have different devices with same label.
- [#169250607](https://www.pivotaltracker.com/story/show/169250607)
> #169250607 make device label unique

- src/services/infusion.js
- Update jsDoc in infusion service where needed
[#170192790](https://www.pivotaltracker.com/story/show/170192790)
>  #170192790 update jsDoc in infusion service

- src/http/middlewares/userCheck.js
- src/http/routes.js
- src/tests/device/getdevice.test.js
- src/tests/infusion/createInfusion.test.js
- src/tests/infusion/deleteInfusion.test.js
- Refactor application routes
- Update some permission levels:
- Nurse users can now create infusions
- Nurse users can now get all devices
- Fix failing tests 
[170358860](https://www.pivotaltracker.com/story/show/17035886)
> #170358860 Refactor app routes
